// @ts-nocheck
// 프로토타입 원본 스크립트 — 마운트 후 DOM 위에서 그대로 실행한다.

export default function init() {
  (function(){
    var state={tab:'all',category:'all',expanded:false};var items=Array.from(document.querySelectorAll('.report-item'));var grid=document.getElementById('report-grid');var count=document.getElementById('report-count');var empty=document.getElementById('report-empty');var load=document.getElementById('load-reports');var sort=document.getElementById('report-sort');
    function render(){var verified=document.getElementById('verified-filter').checked;var publicOnly=document.getElementById('public-filter').checked;var minAccuracy=Number(document.getElementById('accuracy-filter').value);var matches=items.filter(function(item){return(state.tab==='all'?true:state.tab==='mine'?item.dataset.mine==='true':item.dataset.subscribed==='true')&&(state.category==='all'||item.dataset.category===state.category)&&(!verified||item.dataset.verified==='true')&&(!publicOnly||item.dataset.public==='true')&&Number(item.dataset.accuracy)>=minAccuracy;});var cards=matches.filter(function(item){return item.classList.contains('report-card');});cards.sort(function(a,b){var key=sort.value==='accuracy'?'accuracy':sort.value==='popular'?'popularity':'date';return Number(b.dataset[key])-Number(a.dataset[key]);}).forEach(function(card){grid.appendChild(card);});items.forEach(function(item){item.hidden=matches.indexOf(item)<0||(!state.expanded&&item.classList.contains('extra-report'));});empty.hidden=matches.length>0;load.hidden=state.expanded||!matches.some(function(item){return item.classList.contains('extra-report');});count.textContent=matches.length?(state.tab==='all'&&state.category==='all'&&!verified&&!publicOnly&&!minAccuracy?'284':matches.length):'0';}
    document.querySelectorAll('[data-report-tab]').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('[data-report-tab]').forEach(function(b){b.classList.remove('active');});button.classList.add('active');state.tab=button.dataset.reportTab;render();});});
    document.querySelectorAll('[data-report-category]').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('[data-report-category]').forEach(function(b){b.classList.remove('active');});button.classList.add('active');state.category=button.dataset.reportCategory;render();});});
    ['verified-filter','public-filter','accuracy-filter'].forEach(function(id){document.getElementById(id).addEventListener('change',render);});sort.addEventListener('change',render);load.addEventListener('click',function(){state.expanded=true;render();});
    document.getElementById('report-filter-toggle').addEventListener('click',function(){var panel=document.getElementById('report-detail-filter');panel.hidden=!panel.hidden;this.setAttribute('aria-expanded',String(!panel.hidden));});document.getElementById('filter-reset').addEventListener('click',function(){document.getElementById('verified-filter').checked=false;document.getElementById('public-filter').checked=false;document.getElementById('accuracy-filter').value='0';render();});
    document.querySelectorAll('.report-bookmark').forEach(function(button){button.addEventListener('click',function(){var active=this.getAttribute('aria-pressed')==='true';this.setAttribute('aria-pressed',String(!active));this.textContent=active?'☆':'★';});});
    var modal=document.getElementById('report-compose-modal');function closeCompose(){modal.hidden=true;document.body.classList.remove('modal-open');document.getElementById('report-write').focus();}document.getElementById('report-write').addEventListener('click',function(){modal.hidden=false;document.body.classList.add('modal-open');setTimeout(function(){document.getElementById('compose-report-title').focus();},0);});modal.querySelectorAll('[data-compose-close],.report-compose-backdrop').forEach(function(button){button.addEventListener('click',closeCompose);});document.getElementById('compose-start').addEventListener('click',function(){document.getElementById('compose-status').hidden=false;});document.addEventListener('keydown',function(event){if(event.key==='Escape'&&!modal.hidden)closeCompose();});render();
  })();}
