export default function Reports() {
  return (
    <>
      <main className={"main"}><div className={"main-inner reports-shell"}>
        <header className={"reports-hero"}><div><h1>리포트</h1><p>검증된 예측가들의 시장 인사이트를 만나보세요.</p></div><button className={"report-write-button"} id={"report-write"} type={"button"}><span aria-hidden={"true"}>✎</span> 리포트 작성</button></header>
        <nav className={"report-main-tabs"} aria-label={"리포트 범위"}><button className={"active"} type={"button"} data-report-tab={"all"}>전체 리포트</button><button type={"button"} data-report-tab={"subscribed"}>구독 중 <b>8</b></button><button type={"button"} data-report-tab={"mine"}>내가 쓴 리포트 <b>3</b></button></nav>
        <section className={"reports-toolbar"} aria-label={"리포트 탐색 도구"}>
          <div className={"report-category-tabs"}><button className={"active"} type={"button"} data-report-category={"all"}>전체</button><button type={"button"} data-report-category={"반도체"}>반도체</button><button type={"button"} data-report-category={"AI·소프트웨어"}>AI·소프트웨어</button><button type={"button"} data-report-category={"2차전지"}>2차전지</button><button type={"button"} data-report-category={"바이오"}>바이오</button><button type={"button"} data-report-category={"금융"}>금융</button><button type={"button"} data-report-category={"매크로"}>매크로</button></div>
          <div className={"report-toolbar-actions"}><label className={"report-sort"}><span className={"sr-only"}>정렬</span><select id={"report-sort"}><option value={"newest"}>최신순</option><option value={"accuracy"}>적중률순</option><option value={"popular"}>인기순</option></select></label><button className={"report-filter-button"} id={"report-filter-toggle"} type={"button"} aria-expanded={"false"}>상세 필터 <span aria-hidden={"true"}>≡</span></button><strong>총 <span id={"report-count"}>284</span>개</strong></div>
        </section>
        <section className={"report-detail-filter"} id={"report-detail-filter"} hidden><label><input type={"checkbox"} id={"verified-filter"} /><span></span> 검증된 예측가만</label><label><input type={"checkbox"} id={"public-filter"} /><span></span> 공개 리포트만</label><label>최소 적중률 <select id={"accuracy-filter"}><option value={"0"}>전체</option><option value={"70"}>70% 이상</option><option value={"75"}>75% 이상</option></select></label><button type={"button"} id={"filter-reset"}>필터 초기화</button></section>

        <article className={"featured-report report-item"} data-category={"반도체"} data-subscribed={"true"} data-verified={"true"} data-public={"true"} data-accuracy={"82.4"} data-date={"20260826"} data-popularity={"3200"}>
          <div className={"featured-author"}><div className={"report-avatar avatar-trainer"} aria-hidden={"true"}>반</div><strong>반도체훈련소 <i title={"검증된 예측가"}>✓</i></strong><span>신뢰도 82.4</span><p>♙ 12.3K 구독중</p></div>
          <div className={"featured-copy"}><em>⬟ 예측 근거 검증됨</em><h2>HBM4 경쟁 구도와 국내 수혜주</h2><p>HBM4 양산 일정과 주요 공급망 변화를 바탕으로 핵심 수혜 기업을 분석합니다.</p><div className={"report-tags"}><span>반도체</span><span>HBM</span><span>산업분석</span></div><footer><time dateTime={"2026-08-26"}>2026.08.26</time><i>·</i><span>12분</span><i>·</i><b>공개 리포트</b></footer></div>
          <div className={"featured-visual"}><img src={"/assets/report-hbm4-feature-v1.png"} alt={"반도체 칩과 상승 추세 그래프를 표현한 HBM4 리포트 이미지"} /><div><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button><span>◉ 3.2K</span><span>▣ 18</span></div></div>
        </article>

        <section className={"report-grid"} id={"report-grid"} aria-label={"리포트 목록"}>
          <article className={"report-card report-item"} data-category={"반도체"} data-subscribed={"false"} data-mine={"true"} data-verified={"false"} data-public={"true"} data-accuracy={"66"} data-date={"20260827"} data-popularity={"1180"}><header><span className={"mini-author"}><i className={"avatar-ai"}>안</i><b>안테나님</b></span><strong>적중률 66.0%</strong></header><h3>HBM4 공급망 단계별 수혜 점검</h3><p>양산 일정과 후공정 장비 수주 흐름을 단계별로 나눠 수혜 구간을 정리했습니다.</p><div className={"report-tags"}><span>반도체</span><span>HBM</span><span>공급망</span></div><footer><span>2026.08.27　·　11분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"매크로"} data-subscribed={"false"} data-mine={"true"} data-verified={"false"} data-public={"true"} data-accuracy={"66"} data-date={"20260821"} data-popularity={"760"}><header><span className={"mini-author"}><i className={"avatar-ai"}>안</i><b>안테나님</b></span><strong>적중률 66.0%</strong></header><h3>환율 1,300원대에서의 업종별 민감도</h3><p>수출주와 내수주의 환율 민감도를 과거 구간과 비교해 정리했습니다.</p><div className={"report-tags"}><span>매크로</span><span>환율</span><span>업종</span></div><footer><span>2026.08.21　·　9분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"2차전지"} data-subscribed={"false"} data-mine={"true"} data-verified={"false"} data-public={"false"} data-accuracy={"66"} data-date={"20260818"} data-popularity={"320"}><header><span className={"mini-author"}><i className={"avatar-ai"}>안</i><b>안테나님</b></span><strong>적중률 66.0%</strong></header><h3>2차전지 재고 사이클 중간 점검 <small>✎ 임시 저장</small></h3><p>셀·소재 업체의 재고 회전 지표를 모아 사이클 위치를 가늠해봤습니다. 작성 중인 초안입니다.</p><div className={"report-tags"}><span>2차전지</span><span>재고</span><span>사이클</span></div><footer><span>2026.08.18　·　7분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"반도체"} data-subscribed={"true"} data-verified={"true"} data-public={"false"} data-accuracy={"72.4"} data-date={"20260825"} data-popularity={"2460"}><header><span className={"mini-author"}><i className={"avatar-fairy"}>실</i><b>실속요정</b><em>✓</em></span><strong>적중률 72.4%</strong></header><h3>메모리 업사이클, 어디까지 왔나 <small>🔒 구독자 전용</small></h3><p>메모리 가격 반등의 구조적 요인과 업사이클 지속 가능성을 점검합니다.</p><div className={"report-tags"}><span>반도체</span><span>메모리</span><span>사이클</span></div><footer><span>2026.08.25　·　10분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"금융"} data-subscribed={"true"} data-verified={"true"} data-public={"true"} data-accuracy={"69.8"} data-date={"20260825"} data-popularity={"2190"}><header><span className={"mini-author"}><i className={"avatar-hunter"}>데</i><b>데이터헌터</b><em>✓</em></span><strong>적중률 69.8%</strong></header><h3>금리 인하 이후 성장주 전략</h3><p>금리 사이클 전환 구간에서 수혜가 기대되는 성장주 섹터와 종목을 제시합니다.</p><div className={"report-tags"}><span>금융</span><span>성장주</span><span>전략</span></div><footer><span>2026.08.25　·　11분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"AI·소프트웨어"} data-subscribed={"true"} data-verified={"true"} data-public={"true"} data-accuracy={"82.4"} data-date={"20260825"} data-popularity={"2880"}><header><span className={"mini-author"}><i className={"avatar-trainer"}>반</i><b>반도체훈련소</b><em>✓</em></span><strong>신뢰도 82.4</strong></header><h3>AI 데이터센터 전력 수요 분석</h3><p>데이터센터 전력 수요 급증과 전력 인프라 기업의 중장기 성장성을 분석합니다.</p><div className={"report-tags"}><span>AI 인프라</span><span>전력</span><span>데이터센터</span></div><footer><span>2026.08.25　·　12분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"2차전지"} data-subscribed={"false"} data-verified={"true"} data-public={"false"} data-accuracy={"68.1"} data-date={"20260824"} data-popularity={"1820"}><header><span className={"mini-author"}><i className={"avatar-value"}>가</i><b>가치투자자</b><em>✓</em></span><strong>적중률 68.1%</strong></header><h3>2차전지 실적 바닥 확인하기 <small>🔒 구독자 전용</small></h3><p>2차전지 주요 기업들의 실적 바닥 신호와 회복 시점을 정리했습니다.</p><div className={"report-tags"}><span>2차전지</span><span>실적</span><span>회복</span></div><footer><span>2026.08.24　·　9분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"바이오"} data-subscribed={"true"} data-verified={"true"} data-public={"true"} data-accuracy={"72.4"} data-date={"20260823"} data-popularity={"1710"}><header><span className={"mini-author"}><i className={"avatar-fairy"}>실</i><b>실속요정</b><em>✓</em></span><strong>적중률 72.4%</strong></header><h3>바이오 플랫폼 기업 체크포인트</h3><p>플랫폼 기술 경쟁력과 파이프라인 가치를 기준으로 투자 포인트를 정리합니다.</p><div className={"report-tags"}><span>바이오</span><span>플랫폼</span><span>R&amp;D</span></div><footer><span>2026.08.23　·　10분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item"} data-category={"매크로"} data-subscribed={"false"} data-verified={"true"} data-public={"false"} data-accuracy={"69.8"} data-date={"20260823"} data-popularity={"1940"}><header><span className={"mini-author"}><i className={"avatar-hunter"}>데</i><b>데이터헌터</b><em>✓</em></span><strong>적중률 69.8%</strong></header><h3>외국인 수급으로 보는 코스피 <small>🔒 구독자 전용</small></h3><p>외국인 수급 패턴과 업종별 순매수 전환 신호를 데이터로 분석했습니다.</p><div className={"report-tags"}><span>매크로</span><span>외국인 수급</span><span>코스피</span></div><footer><span>2026.08.23　·　11분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item extra-report"} data-category={"AI·소프트웨어"} data-subscribed={"true"} data-verified={"false"} data-public={"true"} data-accuracy={"75.6"} data-date={"20260822"} data-popularity={"2310"}><header><span className={"mini-author"}><i className={"avatar-ai"}>A</i><b>AI레이더</b></span><strong>적중률 75.6%</strong></header><h3>온디바이스 AI 밸류체인 지도</h3><p>모바일과 엣지 디바이스의 AI 확산에 따른 핵심 밸류체인을 살펴봅니다.</p><div className={"report-tags"}><span>AI</span><span>온디바이스</span><span>밸류체인</span></div><footer><span>2026.08.22　·　13분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item extra-report"} data-category={"금융"} data-subscribed={"false"} data-verified={"true"} data-public={"true"} data-accuracy={"71.2"} data-date={"20260821"} data-popularity={"1420"}><header><span className={"mini-author"}><i className={"avatar-value"}>가</i><b>가치투자자</b><em>✓</em></span><strong>적중률 71.2%</strong></header><h3>은행주 배당 여력 점검</h3><p>자본비율과 주주환원 정책을 중심으로 은행주의 배당 여력을 비교합니다.</p><div className={"report-tags"}><span>금융</span><span>은행</span><span>배당</span></div><footer><span>2026.08.21　·　8분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
          <article className={"report-card report-item extra-report"} data-category={"반도체"} data-subscribed={"true"} data-verified={"true"} data-public={"true"} data-accuracy={"77.9"} data-date={"20260820"} data-popularity={"2760"}><header><span className={"mini-author"}><i className={"avatar-trainer"}>반</i><b>반도체훈련소</b><em>✓</em></span><strong>적중률 77.9%</strong></header><h3>글로벌 반도체 재고 사이클</h3><p>주요 제조사의 재고 일수와 출하 흐름을 통해 업황의 다음 변곡점을 짚습니다.</p><div className={"report-tags"}><span>반도체</span><span>재고</span><span>글로벌</span></div><footer><span>2026.08.20　·　14분</span><button className={"report-bookmark"} type={"button"} aria-label={"북마크"} aria-pressed={"false"}>☆</button></footer></article>
        </section>
        <p className={"report-empty"} id={"report-empty"} hidden>조건에 맞는 리포트가 없습니다.</p><button className={"load-reports"} id={"load-reports"} type={"button"}>더 보기 <span aria-hidden={"true"}>⌄</span></button>
      </div></main>

      <div className={"report-compose-modal"} id={"report-compose-modal"} hidden><button className={"report-compose-backdrop"} type={"button"} aria-label={"닫기"}></button><section className={"report-compose-dialog"} role={"dialog"} aria-modal={"true"} aria-labelledby={"compose-title"}><header><div><span>REPORT STUDIO</span><h2 id={"compose-title"}>새 리포트 작성</h2></div><button type={"button"} data-compose-close aria-label={"닫기"}>×</button></header><label>제목<input id={"compose-report-title"} type={"text"} placeholder={"리포트 제목을 입력하세요"} /></label><label>분야<select><option>반도체</option><option>AI·소프트웨어</option><option>2차전지</option><option>바이오</option><option>금융</option><option>매크로</option></select></label><label>한 줄 요약<textarea placeholder={"독자에게 보여줄 핵심 내용을 작성하세요"} defaultValue={""}></textarea></label><footer><button type={"button"} data-compose-close>취소</button><button type={"button"} id={"compose-start"}>작성 시작</button></footer><p id={"compose-status"} role={"status"} hidden>작성 화면을 준비했어요. 이 프로토타입에서는 초안 상태로 저장됩니다.</p></section></div>
    </>
  )
}
